#define Uses_alloca
#define Uses_AllocLocal
#define Uses_chdir
#define Uses_ctype
#define Uses_dir
#define Uses_dirent
#define Uses_fcntl
#define Uses_filelength
#define Uses_fpbase
#define Uses_fpstream
#define Uses_FullSingleKeySymbols
#define Uses_getcwd
#define Uses_glob
#define Uses_HaveLFNs
#define Uses_ifpstream
#define Uses_iopstream
#define Uses_IOS_BIN
#define Uses_ipstream
#define Uses_limits
#define Uses_MsgBox
#define Uses_ofpstream
#define Uses_opstream
#define Uses_pstream
#define Uses_PubStreamBuf
#define Uses_snprintf
#define Uses_stdio
#define Uses_stdlib
#define Uses_string
#define Uses_sys_stat
#define Uses_T1Label
#define Uses_TApplication
#define Uses_TBackground
#define Uses_TButton
#define Uses_TCalcDisplay
#define Uses_TCalculator
#define Uses_TChDirDialog
#define Uses_TCheckBoxes
#define Uses_TCluster
#define Uses_TCollection
#define Uses_TColorDialog
#define Uses_TColorDisplay
#define Uses_TColorGroup
#define Uses_TColorGroupList
#define Uses_TColorItem
#define Uses_TColorItemList
#define Uses_TColorSelector
#define Uses_TCommandSet
#define Uses_TDeskTop
#define Uses_TDialog
#define Uses_TDirCollection
#define Uses_TDirEntry
#define Uses_TDirListBox
#define Uses_TDrawBuffer
#define Uses_TEditor
#define Uses_TEditorApp
#define Uses_TEditWindow
#define Uses_TEvent
#define Uses_TEventQueue
#define Uses_TFileCollection
#define Uses_TFileDialog
#define Uses_TFileEditor
#define Uses_TFileInfoPane
#define Uses_TFileInputLine
#define Uses_TFileList
#define Uses_TFileViewer
#define Uses_TFilterValidator
#define Uses_TFindDialogRec
#define Uses_TFrame
#define Uses_TGKey
#define Uses_TGroup
#define Uses_THelpFile
#define Uses_THelpWindow
#define Uses_THistory
#define Uses_THistoryViewer
#define Uses_THistoryWindow
#define Uses_TIndicator
#define Uses_TInputLine
#define Uses_TKeys
#define Uses_TKeys_Extended
#define Uses_TLabel
#define Uses_TListBox
#define Uses_TListViewer
#define Uses_TMacroCollection
#define Uses_TMemo
#define Uses_TMenu
#define Uses_TMenuBar
#define Uses_TMenuBox
#define Uses_TMenuItem
#define Uses_TMenuView
#define Uses_TMonoSelector
#define Uses_TMouse
#define Uses_TNSCollection
#define Uses_TNSSortedCollection
#define Uses_TObject
#define Uses_TPalette
#define Uses_TParamText
#define Uses_TPoint
#define Uses_TPReadObjects
#define Uses_TProgram
#define Uses_TPWrittenObjects
#define Uses_TPXPictureValidator
#define Uses_TRadioButtons
#define Uses_TRangeValidator
#define Uses_TRect
#define Uses_TReplaceDialogRec
#define Uses_TResourceCollection
#define Uses_TResourceFile
#define Uses_TResourceItem
#define Uses_TScreen
#define Uses_TScrollBar
#define Uses_TScroller
#define Uses_TSearchRec
#define Uses_TSItem
#define Uses_TSortedCollection
#define Uses_TSortedListBox
#define Uses_TStaticText
#define Uses_TStatusDef
#define Uses_TStatusItem
#define Uses_TStatusLine
#define Uses_TStreamable
#define Uses_TStreamableClass
#define Uses_TStreamableTypes
#define Uses_TStrIndexRec
#define Uses_TStringCollection
#define Uses_TStringList
#define Uses_TStringLookupValidator
#define Uses_TStrListMaker
#define Uses_TSubMenu
#define Uses_TTerminal
#define Uses_TTextDevice
#define Uses_TValidator
#define Uses_TVCodePage
#define Uses_TVConfigFile
#define Uses_TVEdConstant
#define Uses_TVEdMac
#define Uses_TView
#define Uses_TVOSClipboard
#define Uses_TVPartitionTree556
#define Uses_TWindow
#define Uses_unistd
